var mongoose = require('mongoose');
module.exports = mongoose.model("believer", new mongoose.Schema({
    believercode: { type: String, required: true },
    title: { type: String, required: true },
    firstname: { type: String, required: true },
    middlename: { type: String, require: false },
    lastname: { type: String, require: true },
    phonenumber: { type: String, required: false },
    device_id: { type: String, required: false },
    diocode: { type: String, required: true },
    dioname: { type: String, required: true },
    churchid: { type: String, required: true },
    churchcode: { type: String, required: true },
    churchname: { type: String, required: true },
    communityid: { type: String, required: true },
    communitycode: { type: String, required: true },
    communityname: { type: String, required: true },
    profilepicture: { type: String, required: false },
    email: { type: String, required: false },
    gender: { type: String, required: true },
    dob: { type: Object, required: true },
    status: { type: String, required: true },
    healthinfo: { type: String, default: 'None' },
    nationality: { type: String, required: true },
    jobtitle: { type: String, required: true },
    regdate: { type: String, required: true },
    baptismstatus: { type: String, required: true },
    maritalstatus: { type: String, default: 'no' },
    kipaimarastatus: { type: String, default: 'no' },
    participationlevel: { type: Array, default: [] },
    residenceadress: { type: Object, required: true },
    relatives: { type: Array, default: [] },
    hobbies: { type: Array, default: [] }
}, { timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } }), "believer");